### ISSUE TITLE
Adding scala to additionalLanguages in prism breaks Docusaurus V2

### ISSUE THREAD

**Issue by Kevin-Lee** [facebook/docusaurus#5013]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io
- [X] I have read the console error message carefully (if applicable)

### Description
Adding `scala` to `additionalLanguages` in `prism` breaks Docusaurus V2.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes I have.

## Steps to reproduce

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Write your steps here:)

1. Open the `docusaurus.config.js` file.
1. Add the following `prism` setting to right below `foot` (just the same as the default structure of the config generated by `npx @docusaurus/init@latest init website classic`)
   ```javascript
   prism: {
       additionalLanguages: ["scala"]
   }
   ```
1. Save
1. The result on the right-hand side is just a blank page.

## Steps to reproduce on the local environment
Additional instructions to reproduce on the local machine,

1. Create a new Docusaurus V2 site
   ```shell
   npx @docusaurus/init@latest init website classic
   cd website
   npm start
1. Acess http://localhost:3000 to Make sure the website is fine.
1. Open the `docusaurus.config.js` file
   ```shell
   vim docusaurus.config.js
   ```
1. Add the following `additionalLanguages` to `prism`.
   ```js
   prism: {
     additionalLanguages: ['scala'],
   },
   ```
1. Start the Docusaurus again
   ```shell
   npm start
   ```
1. Acess http://localhost:3000 again
1. Get the blank page.

NOTE: `npm start` on the console shows no error
```shell
npm start

> website@0.0.0 start /private/tmp/docs/website
> docusaurus start

Starting the development server...
Docusaurus website is running at "http://localhost:3000/".

✔ Client
  Compiled successfully in 1.65s

ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /private/tmp/docs/website
ℹ ｢wds｣: 404s will fallback to /index.html
```

## Expected behavior

Just a normal Docusaurus V2 website when accessing http://localhost:3000

## Actual behavior

A blank page when accessing http://localhost:3000

Chrome's Developer Tools console shows this error.
<img width="905" alt="Screen Shot 2021-06-19 at 5 28 29 pm" src="https://user-images.githubusercontent.com/2307335/122635551-f5a39400-d127-11eb-83bc-fcde26464214.png">

Here is the downloaded log.
[localhost-1624087717210.log](https://github.com/facebook/docusaurus/files/6680237/localhost-1624087717210.log)

## Your environment

- Public source code: Tested locally and it's so easy to reproduce with the steps I provided.
- Public site URL: Tested locally and it's so easy to reproduce with the steps I provided.

- Node Environment
  ```shell
  $ npm --version
  6.14.11

  $ node --version
   v14.16.0
  ```
- Chrome: `91.0.4472.106`
- Operating System: macOS `Big Sur 11.4`

- Docusaurus version: `2.0.0-beta.1`

## Reproducible demo

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

https://codesandbox.io/s/happy-hugle-q0kr8?file=/docusaurus.config.js:1975-2026

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)

**Comment by Kevin-Lee** [comment]
I found that it works with Docusarus `2.0.0-alpha.74`, and `prism-react-renderer` version `1.1.1` but it doesn't with `1.2.1`.

**Comment by Kevin-Lee** [comment]
i just found that adding `'java'` before `'scala'` solves the issue, but I'm not sure if it gives me the proper syntax highlighting for Scala.
```js
prism: {
  additionalLanguages: [
    'java',
    'scala',
  ],
},
```
Shouldn't it just work by `'scala'` itself? It definitely worked when I used `2.0.0-alpha.6x` versions. I think the version of `prism-react-renderer` was `1.1.1` though at that time.

**Comment by Josh-Cena** [comment]
Yes, this is reported in #4799 as well. I think it's best if we can add it in the docs

**Comment by lex111** [comment]
This is how Prism.js works, to use Scala's syntax highlighting you need to include Java as well (since one depends on the other). To reduce the bundle size we remove unused syntax highlighting languages, so you may have similar issue (see #4799 for more detail).

**Comment by Josh-Cena** [comment]
> This is how Prism.js works, to use Scala's syntax highlighting you need to include Java as well (since one depends on the other).

I personally find this very counterintuitive. Can we help the users by, say, automatically adding `java` to the array if we find `scala`?

**Comment by Kevin-Lee** [comment]
@Josh-Cena Thanks. Oh... I thought that was a different issue since the error message is different. Mine is `Cannot set property 'triple-quoted-string' of undefined` whereas the other one is `Cannot find module './prism-scala'`.

@lex111 As Josh said, it would be much better if `java` is automatically added to `additionalLanguages` or at least Prism requires Java so that the error message tells what is missing.

I reported it yesterday but found it earlier than #4799 and wasted a few days trying to fix this issue. 😢

**Comment by lex111** [comment]
> Can we help the users by, say, automatically adding java to the array if we find scala

I suppose this applies not only to Scala-Java, there are probably other dependent languages as well. Therefore, it is difficult to somehow help users in this.

@Kevin-Lee sorry about that, but it's quite specific problem because we use `prism-react-renderer`, which include [several dozen languages](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js), and the `additionalLanguages` field is meant to be used by users so that they can add another language.
And I'm not sure if it's a good idea to add something by default to that field. So in case of such problems, it is better to try to search for issues, since then maybe you will find solution for your usecase (maybe we should add the corresponding checkbox item in our bug report template).

**Comment by Josh-Cena** [comment]
I ran a search in prism, and found the following inherited languages (whose base language is not included in `prism-react-renderer`):

- `racket` extends `scheme`;
- `erb`, `crystal` extends `ruby`;
- `idris`, `purescript` extends `haskell`;
- `scala` extends `java`.

IMO `scala` seems like the only common pitfall. Interestingly, I tried adding `erb` without `ruby`, and the site builds successfully despite no highlighting added, meaning that the `scala` case is probably more unique than it seems.

I don't know if an exhaustive fix is possible (Can this be done with joi scheme validation? Or can we patch these sorts of common pitfalls in our own build script when first reading the config?). Documenting it seems like a hack to me (telling users that `scala` cannot be used as standalone although it's definitely an independent language; even `dart` and `kotlin` are usable alone). But either option is better than letting every user go onto GitHub and browse through the issues... I will try opening a PR and address it in whatever way I can

**Comment by slorber** [comment]
Thanks for that list @Josh-Cena 

Normally prism automatically add Java when Scala is used, but as we made an optimization to reduce bundle size it's not anymore the case.

I also think it's possible to apply that with Joi (ie automatically add java when scala is used) and wouldn't mind merging a PR and maintain a config for a few inherited languages. Joi is not the most straightforward lib, but we have a few examples (the blog feed ["all"] is converted to ["rss","atom"] when validating/normalizing options)

**Comment by waldyrious** [comment]
> I can't tell if there's a huge ROI considering there's a good workaround

IMHO the importance of fixing this directly in Docusaurus is heightened by the fact that this happens not just for people trying to use `scala`, which depends on `java` (and that's understandable), but also for people trying to use `java`, which fails unless one adds `scala` as well (which is much less clear), as described in https://github.com/facebook/docusaurus/issues/7209. Not to mention this issue has been raised in various other threads, e.g. #2564, #5443, #10352 (to mention a few).

> I also think it's possible to apply that with Joi (ie automatically add java when scala is used) and wouldn't mind merging a PR and maintain a config for a few inherited languages. Joi is not the most straightforward lib, but we have a few examples (the blog feed ["all"] is converted to ["rss","atom"] when validating/normalizing options)

I suppose you mean this, right?

https://github.com/facebook/docusaurus/blob/eeec303dd773774ed5a023884800da0b061f6942/packages/docusaurus-plugin-content-blog/src/options.ts#L134-L147

Where would one need to make a similar change for the scala/java issue, and possible other language pairs/sets?

**Comment by slorber** [comment]
@waldyrious if you want to give it a try, you could apply normalization logic to our theme options schema here, that you can cover with unit tests

https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/options.ts#L410

That could also be used for the PHP language exception we did here: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/prism-include-languages.ts

Note: it's probably that the order of languages matters. If scala and java have to be added together, the order should probably be the same if a user adds java or scala only.

**Comment by waldyrious** [comment]
Hmm, I never worked with Joi before, but upon studying the syntax a bit, I figured we could use the [`custom()` method](https://joi.dev/api/?v=17.13.3#anycustommethod-description) to implement this logic; I was thinking to replace this:

```js
additionalLanguages: Joi.array()
  .items(PrismLanguage)
  .default(DEFAULT_CONFIG.prism.additionalLanguages),
```

with something like this:

```js
additionalLanguages: Joi.array()
  .items(PrismLanguage)
  .custom((languagesArray) => {
    const hasJava = languagesArray.includes('java');
    const hasScala = languagesArray.includes('scala');

    // Append "scala" if "java" is present and "scala" isn't
    if (hasJava && !hasScala) {
      languagesArray.push('scala');
    }
    // Prepend "java" if "scala" is present and "java" isn't
    if (hasScala && !hasJava) {
      languagesArray.unshift('java');
    }

    return languagesArray;
  })
  .default(DEFAULT_CONFIG.prism.additionalLanguages);
```

(with similar logic for `php` → `markup-templating`, omitted here for conciseness).

Does that match what you had in mind? Or is it too hacky? :sweat_smile:

> Note: it's probably that the order of languages matters. If scala and java have to be added together, the order should probably be the same if a user adds java or scala only.

Yeah, it only works if I have `java, scala` in the array, in this order. If I have `scala, java`, or just `java`, or just `scala`, it fails.

**Comment by slorber** [comment]
Honestly, Joi is a pain to work with 😅 

I don't really care which API of it you use as long as I can clearly see unit tests passing and covering the functionality you implement. The implementation proposed looks fine and good enough to me.

So, as far as I understand, you confirm order actually matters and java should come before scala?

**Comment by waldyrious** [comment]
> Note: if the order matters you'd rather define ordering rules instead of push/unshift, and also cover the case where user provides additionalLanguages: ["scala","java"] or additionalLanguages: ["php","markup-templating"]

I'm not sure I follow. Doesn't the example code above already account for that? I.e. if `java` is present, and `scala` isn't, then `scala` is added to the end (therefore after `java`, and maintaining the necessary order); similarly, if `scala` is present and `java` isn't, then `java` is prepended (therefore before `scala`, and maintaining the necessary order). If both are present, nothing is done. Sure, having both present in the wrong order would not be fixed by this mechanism, but IMHO that's a corner case that I don't feel would be too onerous for the user to fix. I was mostly concerned about the situations where one of the two languages is missing and the solution of adding the other one is completely unintuitive and non-obvious because e.g. they don't have any `java` (or `scala`) code blocks.

**Comment by Josh-Cena** [comment]
I personally disagree: it's equally confusing and unintuitive that the language order matters. We should help users work around these Prism implementation details by exposing an API that functions "as if" `additionalLanguages` is an order-independent collection of languages they actually use.

**Comment by slorber** [comment]
Same opinion. If you get confused by things breaking while adding only one language, now imagine if you add both in the wrong order and it still doesn't work. We want things to work seamlessly, or things to fail with a clear error message. Ideally, we don't want to document anywhere the correct language order, it should be intuitive to use.

**Comment by waldyrious** [comment]
I see your points. So perhaps something like this would be closer to what you were thinking of?

```js
additionalLanguages: Joi.array()
  .items(PrismLanguage)
  .custom((langsArray) => {
    // Filter the array excluding any occurrences of "java" and "scala"
    const newLangsArray = langsArray.filter(lang => lang !== 'java' && lang !== 'scala');

    // Append "java" and "scala" at the end, in this order
    newLangsArray.push('java', 'scala');

    return newLangsArray;
  })
  .default(DEFAULT_CONFIG.prism.additionalLanguages);
```

**Comment by slorber** [comment]
This code is not correct because all users will end up having java/scala support, which would increase the bundle size for all users despite not using prism to highlight these languages

You can extract this sort function as a separate one and write a unit test for it.
You can add a short comment with a link to this issue so that we know why this has been done

**Comment by waldyrious** [comment]
Oh, right, sorry about that, I totally forgot to test the presence of one of the two. It's what I get for responding to discussion threads late at night :sweat_smile:

As for the sorting approach, after revisiting it in a less fleeting manner, I realized it wouldn't be that much cleaner since it would only work if both languages are already present in the array.

Anyway, I feel think this is a good starting point. I'll see if I can submit a proper patch soon.

**Comment by slorber** [comment]
You can sort after adding the missing languages to the array 😄

Honestly what I care about is the unit tests, there's not a single way to implement this.
