### ISSUE TITLE
[v2] Tabs fail to render when they have only one child

### ISSUE THREAD

**Issue by aeneasr** [facebook/docusaurus#3822]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

In a mdx file, write:

```mdx
import Tabs from '@theme/Tabs'
import TabItem from '@theme/TabItem'

<Tabs
  defaultValue="node"
  values={[
    {label: 'NodeJS', value: 'node'},
  ]}>
  <TabItem value="node">
    asdf
  </TabItem>
</Tabs>
```

## Expected behavior

This will fail to render with `index.js?3e4b:6 Uncaught (in promise) TypeError: children.map is not a function` caused by https://github.com/facebook/docusaurus/commit/8c9f9487d6e1035f1fb41f1df228e053977ca6ce and more specifically the removal of https://github.com/facebook/docusaurus/commit/8c9f9487d6e1035f1fb41f1df228e053977ca6ce#diff-5548122e1da708235c90f8d8cc552ffa69c199f1dd82ca505c9577ac7255da73L114

Adding a non-sense tab like so will fix this:

```mdx
import Tabs from '@theme/Tabs'
import TabItem from '@theme/TabItem'

<Tabs
  defaultValue="node"
  values={[
    {label: 'NodeJS', value: 'node'},
  ]}>
  <TabItem value="node">
    asdf
  </TabItem>
  <TabItem value="placeholder" />
</Tabs>
```

## Actual Behavior

Rendering should not fail

## Your Environment

- Docusaurus version used: alpha 69

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by doucol** [comment]
I'm seeing evidence that this has resurfaced with the 2.3 release. We had one page with a single tab in the tabset and it was causing the `TypeError: children.map is not a function` error. Removed the tabset and error disappears.

**Comment by Josh-Cena** [comment]
Let's track the new error in https://github.com/facebook/docusaurus/issues/8591
