### PR TITLE
fix(v2): support rendering of singular tabs

### LINKED ISSUE #3822: [v2] Tabs fail to render when they have only one child
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

In a mdx file, write:

```mdx
import Tabs from '@theme/Tabs'
import TabItem from '@theme/TabItem'

<Tabs
  defaultValue="node"
  values={[
    {label: 'NodeJS', value: 'node'},
  ]}>
  <TabItem value="node">
    asdf
  </TabItem>
</Tabs>
```

## Expected behavior

This will fail to render with `index.js?3e4b:6 Uncaught (in promise) TypeError: children.map is not a function` caused by https://github.com/facebook/docusaurus/commit/8c9f9487d6e1035f1fb41f1df228e053977ca6ce and more specifically the removal of https://github.com/facebook/docusaurus/commit/8c9f9487d6e1035f1fb41f1df228e053977ca6ce#diff-5548122e1da708235c90f8d8cc552ffa69c199f1dd82ca505c9577ac7255da73L114

Adding a non-sense tab like so will fix this:

```mdx
import Tabs from '@theme/Tabs'
import TabItem from '@theme/TabItem'

<Tabs
  defaultValue="node"
  values={[
    {label: 'NodeJS', value: 'node'},
  ]}>
  <TabItem value="node">
    asdf
  </TabItem>
  <TabItem value="placeholder" />
</Tabs>
```

## Actual Behavior

Rendering should not fail

## Your Environment

- Docusaurus version used: alpha 69

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

### PR DESCRIPTION
**Pull request by aeneasr**
Closes #3822

## Motivation

(Write your motivation here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

**Comment by aeneasr** [comment]
Looks like a tab definition is failing, not sur ehow to fix that - but maybe this can give an idea of what needs to be done!

**Comment by slorber** [comment]
added a fix to your branch, it should work now

**Comment by aeneasr** [comment]
Thank you! Given that this broke all builds for us, is there any chance to have this released in the near future?

**Comment by slorber** [comment]
@aeneasr in the process of adding canary releases, so that users can run on master code easily, so you may be able to do so very soon if you urgently need an unreleased fix

**Comment by aeneasr** [comment]
wow that's awesome!

**Comment by slorber** [comment]
@aeneasr a canary dist tag has been published, you can try it and let me know if it works for you?

This fix should be available

**Comment by aeneasr** [comment]
Yes, that works perfectly - thank you!
