### ISSUE TITLE
Failing to build with 2.0: Error: Cannot find module 'wait-file'

### ISSUE THREAD

**Issue by johnnyreilly** [facebook/docusaurus#7868]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When I try to build with Docusaurus 2.0 I experience an error which you can see [here](https://github.com/johnnyreilly/blog.johnnyreilly.com/runs/7605731556?check_suite_focus=true)

```shell
> docusaurus build

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'wait-file'
Require stack:
- /home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/webpack/plugins/WaitPlugin.js
- /home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/webpack/server.js
- /home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/commands/build.js
- /home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:[77](https://github.com/johnnyreilly/blog.johnnyreilly.com/runs/7605731556?check_suite_focus=true#step:4:78)8:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/webpack/plugins/WaitPlugin.js:10:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:9[81](https://github.com/johnnyreilly/blog.johnnyreilly.com/runs/7605731556?check_suite_focus=true#step:4:82):32)
    at Function.Module._load (node:internal/modules/cjs/loader:[82](https://github.com/johnnyreilly/blog.johnnyreilly.com/runs/7605731556?check_suite_focus=true#step:4:83)2:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/webpack/plugins/WaitPlugin.js',
    '/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/webpack/server.js',
    '/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/commands/build.js',
    '/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/index.js'
  ]
}
Error: Process completed with exit code 1.
```

### Steps to reproduce

Try to build this branch: https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/276

### Expected behavior

Build should succeed

### Actual behavior

Build should fail - see above and https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/276

### Your environment

- Public source code: https://github.com/johnnyreilly/blog.johnnyreilly.com
- Public site URL: https://blog.johnnyreilly.com
- Docusaurus version used: 2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
What...? We migrated away from `wait-file` [two years ago](https://github.com/facebook/docusaurus/pull/3765)! Could you try installing it locally?

**Comment by Josh-Cena** [comment]
Never mind, this file is corrupted somehow:

https://unpkg.com/browse/@docusaurus/core@2.0.0/lib/webpack/plugins/WaitPlugin.js

**Comment by johnnyreilly** [comment]
https://github.com/johnnyreilly/blog.johnnyreilly.com/actions/runs/2772875207

Adding it directly to the project fixes the build by the looks of it: `yarn add wait-file -D`

**Comment by Josh-Cena** [comment]
You shouldn't need to... that file is suddenly reverted to the 2-year-ago version

**Comment by johnnyreilly** [comment]
Super weird

**Comment by slorber** [comment]
fixed in 2.0.1

**Comment by johnnyreilly** [comment]
I think you can still republish - if I recall there's like a 48 window where you can do that with npm modules

**Comment by Josh-Cena** [comment]
Yes, that's what I remember too.

**Comment by rguldener** [comment]
Also getting this error after upgrading to 2.0.0, just ran `npm install` on 2.0.0 10 minutes ago (so I guess the 2.0.0 packages haven't been patched retroactively yet?).
Is 2.0.1 available somewhere or how can I get the fixed version?

As a side note, GitHub still lists 2.0.0-rc1 as the latest release the changelog for 2.0.0 is also missing: https://docusaurus.io/changelog
Let me know if I should open separate issues for these

**Comment by Josh-Cena** [comment]
2.0.1 was released more than 24 hours ago. See https://www.npmjs.com/package/@docusaurus/core?activeTab=versions

@slorber Could you update the GitHub release?

**Comment by rguldener** [comment]
Thanks for the swift reply @Josh-Cena, didn't check NPM and didn't realize 2.0.1 is out because the docs & everything else only mention 2.0.0. Should have checked NPM I guess :)

I actually followed the update guide and since that also mentioned putting 2.0.0 into package.json that is just what I did: https://docusaurus.io/docs/installation#updating-your-docusaurus-version
Just as a heads up, might be worth changing 2.0.0 to 2.0.1 (or whatever the latest patch is) at least there :)

**Comment by Josh-Cena** [comment]
Yes, we should rename the current version on the website to `2.0.1`. @slorber WDYT?
