### ISSUE TITLE
HTML comments throw compilation error

### ISSUE THREAD

**Issue by chaveamin** [facebook/docusaurus#12066]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

in latest docusaurus version(3.10) HTML comments throw compilation error. it was working fine in previous version(3.9):
```
MDX compilation failed for file "..."
        │ Cause: Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
```
This is the only way to comment in md files.
repo: https://github.com/chaveamin/rtl-theme-docs
live demo: https://docs.designesia.ir/

### Steps to reproduce

Start dev server

### Expected behavior

it should compile without any error

### Actual behavior

An error in the npm console:
```
MDX compilation failed for file "..."
        │ Cause: Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
```

### Your environment

- Public source code: https://github.com/chaveamin/rtl-theme-docs
- Public site URL: https://docs.designesia.ir/
- Docusaurus version used: 3.10
- Environment name and version: Node v24.12.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.
