### ISSUE TITLE
bug resolving multiple markdown links on the same line

### ISSUE THREAD

**Issue by atkinsonm** [facebook/docusaurus#9161]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Since upgrading to 2.4.1 in a dev environment, I have started to get compilation errors relating to markdown links. This bug is not present on 2.4.0.

Example error:

```
Error: Docs markdown link couldn't be resolved: (./003_aws_mac_manual_setup.md) and [006_aws_mac_ansible_setup.md) in "/Users/michael.atkinson/Dev/docs/devxp/desktop-devxp/008_desktop_mac_code_signing.md" for version current
    at Array.forEach (<anonymous>)
```

The line in question:

```
The setup of these Macs is described both in [003_aws_mac_manual_setup](./003_aws_mac_manual_setup.md) and [006_aws_mac_ansible_setup.md](./006_aws_mac_ansible_setup.md).
```

I am seeing other compilation errors of the same type as this example, all in cases where a single line of a markdown file contains more than one relative link to another markdown file. The file name does not seem to make a difference; I have examples using numbers, alphanumerics, and escaped special characters in multiple orientations.

### Steps to reproduce

1. Upgrade an existing docusaurus site to 2.4.1 by updating the package.json
2. Ensure that at least one markdown file contains multiple relative links to other markdown files on a single line
3. build with yarn
4. Run `docusaurus start`
5. Observe compilation errors

### Expected behavior

Site compiles and resolves all valid markdown links

### Actual behavior

Compilation errors, site unusable

### Your environment

- Public source code: N/A, private
- Public site URL: N/A, private
- Docusaurus version used: 2.4.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 114.0.5735.198, Node.js v16.17.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 13.4.1
- docusaurus plugins: "@docusaurus/plugin-google-gtag": "^2.4.1", "@docusaurus/preset-classic": "^2.4.1", "@docusaurus/theme-common": "^2.4.1", "@docusaurus/theme-mermaid": "^2.4.1", "docusaurus-theme-search-typesense": "^0.12.0", "@docusaurus/module-type-aliases": "^2.4.1",

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Your error message and Markdown source don't match: the links are `(./003_aws_mac_manual_setup.md)` and `[006_aws_mac_ansible_setup.md)`, with extra brackets. Could you make sure your source is actually correct?

**Comment by slorber** [comment]
> Your error message and Markdown source don't match: the links are `(./003_aws_mac_manual_setup.md)` and `[006_aws_mac_ansible_setup.md)`, with extra brackets. Could you make sure your source is actually correct?

I'm not sure to understand what you mean here 🤔 

---

Looks like I can reproduce the issue, and it only happens on the first link of a given line?

https://stackblitz.com/edit/github-zg75tv?file=docs%2Fintro.md

![CleanShot 2023-07-21 at 13 33 16@2x](https://github.com/facebook/docusaurus/assets/749374/b6e72f7b-1c8e-4402-8cbb-38fdec84fcd3)

**Comment by atkinsonm** [comment]
> Your error message and Markdown source don't match: the links are `(./003_aws_mac_manual_setup.md)` and `[006_aws_mac_ansible_setup.md)`, with extra brackets. Could you make sure your source is actually correct?

I included this line from my source code:

```md
The setup of these Macs is described both in [003_aws_mac_manual_setup](./003_aws_mac_manual_setup.md) and [006_aws_mac_ansible_setup.md](./006_aws_mac_ansible_setup.md).
```

Please note that there are _two_ correctly formatted markdown links, but yet the error seems to be attempting to glob them together into one.

**Comment by atkinsonm** [comment]
> > Your error message and Markdown source don't match: the links are `(./003_aws_mac_manual_setup.md)` and `[006_aws_mac_ansible_setup.md)`, with extra brackets. Could you make sure your source is actually correct?
> 
> I'm not sure to understand what you mean here 🤔
> 
> Looks like I can reproduce the issue, and it only happens on the first link of a given line?
> 
> https://stackblitz.com/edit/github-zg75tv?file=docs%2Fintro.md
> 
> ![CleanShot 2023-07-21 at 13 33 16@2x](https://user-images.githubusercontent.com/749374/255161788-b6e72f7b-1c8e-4402-8cbb-38fdec84fcd3.png)

The site actually fails to render for me at all, so you've gotten further than I have. This is what I see in the frontend (running a site with `docusaurus start`)

<img width="1696" alt="image" src="https://github.com/facebook/docusaurus/assets/3342243/0d2fc074-006e-4b52-b2bb-78fac706033e">

**Comment by slorber** [comment]
I can also reproduce this bug on the React-Native website, and not sure it happened before the 2.4.1 upgrade.

Example line that produces the problem is not even using the `.md` extension in a Markdown link, but only in text:

```md
After this, you will be able to continue to [Native Modules (iOS)](native-modules-ios) or [Native Modules (Android)](native-modules-android) to add in some code. Make sure to read the README.md within your `MyLibrary` Directory for platform-specific instructions on how to include the project.
```

**Comment by Josh-Cena** [comment]
Does this reproduce in 3.0? Because https://github.com/facebook/docusaurus/pull/8927 is not backported.

**Comment by slorber** [comment]
> Does this reproduce in 3.0? Because https://github.com/facebook/docusaurus/pull/8927 is not backported.

I'm not sure I remember seeing this error, will investigate next week and test this PR changes against the RNW website to see if it works and is safe to backport.

**Comment by slorber** [comment]
Yes the fix hasn't been backported unfortunately.

If we do another 2.x release I may try to backport it, otherwise you can try the v3 beta already: I'm writing the material to let you know how to upgrade right now and it will be published soon.

**Comment by slorber** [comment]
This bug is fixed in v3.0 beta, cf https://stackblitz.com/edit/github-zg75tv?file=package.json
