### ISSUE TITLE
Cannot use SASS after update to 2.0.0-beta.0

### ISSUE THREAD

**Issue by ArtFlag** [facebook/docusaurus#4804]
## 🐛 Bug Report

I was using  2.0.0-alpha72 with SASS without issues, then I ran the yarn upgrade command suggested by docusaurus when using `yarn start`. 

After the update, I had some issues with Webpack 5, so I installed `https-browserify` and `path-browserify` and ran `yarn upgrade`.

Most issues disappeared, bu I still the SASS-related error listed below.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes 

## Expected behavior

The build succeeds after the upgrade. 

## Actual Behavior

I'm getting the following error:

```

✖ Client
  Compiled with some errors in 41.83s

● Server █████████████████████████ building (64%) 1/1 entries 10353/10353 dependencies 3535/3535 modules 0 active


Cannot find module 'sass'
Require stack:
- /Users/a/repos/docs/node_modules/sass-loader/dist/utils.js
- /Users/a/repos/d/node_modules/sass-loader/dist/index.js
- /Users/a/repos/d/node_modules/sass-loader/dist/cjs.js
- /Users/a/repos/d/node_modules/webpack/lib/ProgressPlugin.js
- /Users/a/repos/d/node_modules/webpack/lib/index.js
- /Users/a/repos/d/node_modules/@docusaurus/core/lib/webpack/utils.js
- /Users/a/repos/d/node_modules/@docusaurus/core/lib/webpack/base.js
- /Users/a/repos/d/node_modules/@docusaurus/core/lib/webpack/client.js
- /Users/a/repos/d/node_modules/@docusaurus/core/lib/commands/build.js
- /Users/a/repos/d/node_modules/@docusaurus/core/lib/index.js
- /Users/a/repos/d/node_modules/@docusaurus/core/bin/docusaurus.js
(repeated 3 times)
Client bundle compiled with errors therefore further build is impossible.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Time: 0h:00m:46s
```

Note: I've tried installing the SASS module globally but I get the same error.

## Your Environment

- Docusaurus version used: 2.0.0-beta.0
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): node v15.12.0
- Operating system and version (desktop or mobile): macos 11.3.1

**Comment by slorber** [comment]
@ArtFlag we don't provide official sass support in this repo, and you didn't provide any repo to inspect so. it's difficult to help you

I'm assuming you use docusaurus-plugin-sass, which does not install node-sass or dart-sass for you anymore on latest version and you have to provide your own sass implementation by adding one of those 2 deps yourself, see https://github.com/rlamana/docusaurus-plugin-sass/pull/11)

**Comment by ArtFlag** [comment]
Oops I deleted my package.json from the message while I was editing it. 

Essentially, I think my issue leads to a docs update.

It's not "install the plugin and add it to the conf file" any more, from my experience, and judging by the updated readme of the sass plugin's repo :)   I'll update the docs if I manage to solve my upgrade issue.
