### ISSUE TITLE
Upgrade from 3.4 to 3.5 causes 

### ISSUE THREAD

**Issue by edwarnermedia** [facebook/docusaurus#10629]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Currently I'm seeing the following warnings in the terminal when running yarn start:

[WARNING] {"moduleIdentifier":"/Users/senders/Projects/top-docs/node_modules/@docusaurus/core/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[5].use[0]!/Users/senders/Projects/top-docs/src/theme/DocVersionBanner/index.js","moduleName":"./src/theme/DocVersionBanner/index.js","loc":"8:765-779","message":"export 'useDocsVersion' (imported as 'useDocsVersion') was not found in '@docusaurus/theme-common/internal' (possible exports: AnnouncementBarProvider, BlogAuthorsListViewAllLabel, Collapsible, ColorModeProvider, DEFAULT_SEARCH_TAG, DraftBannerMessage, DraftBannerTitle, ErrorBoundaryError, ErrorBoundaryErrorMessageFallback, ErrorBoundaryTryAgainButton, ErrorCauseBoundary, HtmlClassNameProvider, NavbarProvider, NavbarSecondaryMenuFiller, PageMetadata, PluginHtmlClassNameProvider, ReactContextError, ScrollControllerProvider, SkipToContentFallbackId, SkipToContentLink, ThemeClassNames, ThemedComponent, UnlistedBannerMessage, UnlistedBannerTitle, UnlistedMetadata, composeProviders, containsLineNumbers, createStorageSlot, duplicates, filterDocCardListItems, getPrismCssVariables, groupBy, isMultiColumnFooterLinks, isRegexpStringMatch, isSamePath, keyboardFocusedClassName, listStorageKeys, listTagsByLetters, parseCodeBlockTitle, parseLanguage, parseLines, prefersReducedMotion, processAdmonitionProps, sanitizeTabsChildren, splitNavbarItems, translateBlogAuthorsListPageTitle, translateTagsPageTitle, uniq, useAlternatePageUtils, useAnnouncementBar, useBackToTopButton, useBlogAuthorPageTitle, useBlogTagsPostsPageTitle, useClearQueryString, useCodeWordWrap, useCollapsible, useColorMode, useContextualSearchFilters, useCurrentSidebarCategory, useDateTimeFormat, useDocsPreferredVersion, useEvent, useFilteredAndTreeifiedTOC, useHideableNavbar, useHistoryPopHandler, useHistorySelector, useHomePageRoute, useKeyboardNavigation, useLocalPathname, useLocationChange, useLockBodyScroll, useNavbarMobileSidebar, useNavbarSecondaryMenu, usePluralForm, usePrevious, usePrismTheme, useQueryString, useQueryStringList, useQueryStringValue, useScrollController, useScrollPosition, useScrollPositionBlocker, useSearchLinkCreator, useSearchQueryString, useSmoothScrollTo, useStorageSlot, useTOCHighlight, useTabs, useThemeConfig, useTitleFormatter, useTreeifiedTOC, useWindowSize)"}
[WARNING] {"moduleIdentifier":"/Users/senders/Projects/top-docs/node_modules/@docusaurus/core/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[5].use[0]!/Users/senders/Projects/top-docs/src/theme/helper/JFrog.js","moduleName":"./src/theme/helper/JFrog.js","loc":"11:128-142","message":"export 'useDocsVersion' (imported as 'useDocsVersion') was not found in '@docusaurus/theme-common/internal' (possible exports: AnnouncementBarProvider, BlogAuthorsListViewAllLabel, Collapsible, ColorModeProvider, DEFAULT_SEARCH_TAG, DraftBannerMessage, DraftBannerTitle, ErrorBoundaryError, ErrorBoundaryErrorMessageFallback, ErrorBoundaryTryAgainButton, ErrorCauseBoundary, HtmlClassNameProvider, NavbarProvider, NavbarSecondaryMenuFiller, PageMetadata, PluginHtmlClassNameProvider, ReactContextError, ScrollControllerProvider, SkipToContentFallbackId, SkipToContentLink, ThemeClassNames, ThemedComponent, UnlistedBannerMessage, UnlistedBannerTitle, UnlistedMetadata, composeProviders, containsLineNumbers, createStorageSlot, duplicates, filterDocCardListItems, getPrismCssVariables, groupBy, isMultiColumnFooterLinks, isRegexpStringMatch, isSamePath, keyboardFocusedClassName, listStorageKeys, listTagsByLetters, parseCodeBlockTitle, parseLanguage, parseLines, prefersReducedMotion, processAdmonitionProps, sanitizeTabsChildren, splitNavbarItems, translateBlogAuthorsListPageTitle, translateTagsPageTitle, uniq, useAlternatePageUtils, useAnnouncementBar, useBackToTopButton, useBlogAuthorPageTitle, useBlogTagsPostsPageTitle, useClearQueryString, useCodeWordWrap, useCollapsible, useColorMode, useContextualSearchFilters, useCurrentSidebarCategory, useDateTimeFormat, useDocsPreferredVersion, useEvent, useFilteredAndTreeifiedTOC, useHideableNavbar, useHistoryPopHandler, useHistorySelector, useHomePageRoute, useKeyboardNavigation, useLocalPathname, useLocationChange, useLockBodyScroll, useNavbarMobileSidebar, useNavbarSecondaryMenu, usePluralForm, usePrevious, usePrismTheme, useQueryString, useQueryStringList, useQueryStringValue, useScrollController, useScrollPosition, useScrollPositionBlocker, useSearchLinkCreator, useSearchQueryString, useSmoothScrollTo, useStorageSlot, useTOCHighlight, useTabs, useThemeConfig, useTitleFormatter, useTreeifiedTOC, useWindowSize)"}
client (webpack 5.89.0) compiled with 2 warnings

When running
Uncaught runtime errors:

ERROR
**(0 , _docusaurus_theme_common_internal__WEBPACK_IMPORTED_MODULE_9__.useDocsVersion) is not a function**
TypeError: (0 , _docusaurus_theme_common_internal__WEBPACK_IMPORTED_MODULE_9__.useDocsVersion) is not a function
    at DocVersionBanner (webpack-internal:///./src/theme/DocVersionBanner/index.js:23:1180)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16305:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20069:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21582:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4213:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4277:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27446:7)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26555:12)
    at workLoopSync (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26461:5)

It looks like it's complaining about the use of useDocsVersion:

```
 import { 
   useDocsPreferredVersion, 
   useDocsVersion, 
 } from '@docusaurus/theme-common/internal'; 
```

 The useDocsVersion method is no longer in the node_modules dependency for @docusaurus/theme-common

### Steps to reproduce

When upgrading to Docusaurus to 3.5, (0 , _docusaurus_theme_common_internal__WEBPACK_IMPORTED_MODULE_9__.useDocsVersion) is not a function is shown on underlying pages. 

### Expected behavior

Upgrade would occur to 3.5

### Actual behavior

[localhost-1730318175773.log](https://github.com/user-attachments/files/17578303/localhost-1730318175773.log)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
No repro provided so we can't troubleshoot this.

Most likely it's not a bug. You are using internal Apis that we moved and even mentioned in v3.5 release notes. If you are using internals, you have to understand the tradeoff you make.

**Comment by edwarnermedia** [comment]
Thank you @slorber , where is it mentioned the internal APIs were moved? I do not see it in the change log. Thanks for your help.

**Comment by slorber** [comment]
https://docusaurus.io/blog/releases/3.5#other-changes

![CleanShot 2024-12-05 at 18 24 24](https://github.com/user-attachments/assets/4f26b35d-4488-45f9-8165-8295c2111bb1)

We don't document this as a breaking change because it's considered an internal change. If you swizzle internal theme components, you need to understand what you opt into: it's now your responsibility to sync with our internal changes on upgrades (even minor).

**Comment by edwarnermedia** [comment]
Thank you! We will investigate.
