### ISSUE TITLE
Typecheck fails when updating to 3.5.0/3.5.1

### ISSUE THREAD

**Issue by razzeee** [facebook/docusaurus#10395]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I do think this is not in my part of the code, but in the part that docusaurus manages.

```
❯ yarn typecheck
error TS2318: Cannot find global type 'Array'.

error TS2552: Cannot find name 'Boolean'. Did you mean 'GLboolean'?

error TS2318: Cannot find global type 'Function'.

error TS2318: Cannot find global type 'IArguments'.

error TS2318: Cannot find global type 'Number'.

error TS2318: Cannot find global type 'Object'.

error TS2318: Cannot find global type 'RegExp'.

error TS2318: Cannot find global type 'String'.

error TS2688: Cannot find type definition file for '@docusaurus/theme-classic'.
  The file is in the program because:
    Entry point of type library '@docusaurus/theme-classic' specified in compilerOptions

error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions


Found 10 errors.
```

See https://github.com/flathub-infra/documentation/pull/355

### Reproducible demo

https://github.com/flathub-infra/documentation/pull/355

### Steps to reproduce

1. Checkout
2. Run `yarn`
3. Run `yarn typecheck`

### Expected behavior

It should typecheck without errors

### Actual behavior

It errors

### Your environment

- Public source code: https://github.com/flathub-infra/documentation/pull/355

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
We have not changed anything w.r.t. our typing setup. Are you using Yarn PnP? Does the node_modules linker work? The PR contains more than just a version bump.

**Comment by slorber** [comment]
Sorry but we can't accept this PR as a legit minimal repro considering your repo is not minimal and the PR also do other things (bump node, enable corepack, upgrade yarn 1 to yarn 4...)

You can see for yourself that a minimal repro is able to typecheck: https://docusaurus.new/stackblitz-ts

We'll eventually reopen and consider it a valid bug report once you provide a minimal repro

**Comment by razzeee** [comment]
Weird, seems to indeed be the update to yarn 4. At the time of upgrading, I couldn't get the pipelines to work without that, but not it just worked. So I'll guess we stay on yarn 1 a bit longer.

Thank you.
